language: android
jdk: oraclejdk8
addons:
  apt:
    packages:
    - realpath
    - xvfb
before_install:
- git clone --depth=1 https://github.com/secure-software-engineering/DroidBench.git
  /tmp/DroidBench
install:
- mvn clean install -DskipTests=true -B -q
script:
- xvfb-run mvn clean verify -B -q
- bash ./dependent-projects-trigger.sh $AUTH_TOKEN
- mvn generate-sources
- bash ./upload-javascript.sh $GH_TOKEN
- ./build-maven-jars.py "install -Dgpg.skip"
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib"
env:
  global:
    - secure: KcugjQYnBqeZ7XenZD5QY7jhekVPO0QpQyjDUteLytaokhyRK2g6eNvr/pPerN2uWUvsPwO18P9F+oOupge1cpPZf4cEY8RzLIromyUoRWd6JA0SKciUYdN2kSqnC4uZSJGXeGLoroyEEL4Q2sqimpkbIGxgxYtVniWgJULOyR4=
    - secure: jacvGPYX4ugG/HgwJEEpWnllWsS/ipX+qRJ7qM5mbDYryeqsz0eiaxBxQ6IpDyj0v6O4DUi74lSQs/UxCWcUxvOn/5AweCZfoF1U8vt1xivanR4MbC2kr6rJ6ohICuJ4PHDS4IffncgaP3Y8cfExHq6+d0tbibYkjRIiMUGpSik=
